server:
  port: 1111
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mulholland0318/mdcproject
          username: mulholland0318
          password: github1986
          default-label: master
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://master:8089/eureka/,http://backTwo:8090/eureka/,http://backThree:8091/eureka/
    register-with-eureka: true
    fetch-registry: false