server:
  port: 5566
spring:
  application:
    name: server
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:zhangsan@localhost:8089/eureka/,http://localhost:8090/eureka/,http://localhost:8091/eureka/
    fetch-registry: true
    register-with-eureka: true #向注册中心注册服务