spring:
  application:
    name: api-gateway
server:
  port: 80
zuul:
  routes:
    api-a:
       path: /api-a/**
       serviceId: SERVICE-A
    api-b:
       path: /api-b/**
       serviceId: service-b
    api-a-url:
       path: /api-a-url/**
       url: http://localhost:5566/
    baidu:
       path: /baidu/**
       url: http://www.baidu.com/
    mdachu:
      path: /**
      serviceId: ribbonServer
eureka:
  instance:
    hostname: localhost-${server.port}
  client:
    register-with-eureka: false #不向注册中心注册自己，只作为服务
    fetch-registry: true #发现服务
    service-url:
      defaultZone: http://localhost:8089/eureka/,http://localhost:8090/eureka/,http://localhost:8091/eureka/ #逗号处不能存在空格
